version: "3.8"
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "My.password.123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  db_mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - "./my-datavolume:/var/lib/mysql"