//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Car {
            get {
                return ResourceManager.GetString("Car", resourceCulture);
            }
        }
        
        public static string CarAccess {
            get {
                return ResourceManager.GetString("CarAccess", resourceCulture);
            }
        }
        
        public static string CarAccessType {
            get {
                return ResourceManager.GetString("CarAccessType", resourceCulture);
            }
        }
        
        public static string CarErrorCode {
            get {
                return ResourceManager.GetString("CarErrorCode", resourceCulture);
            }
        }
        
        public static string CarMark {
            get {
                return ResourceManager.GetString("CarMark", resourceCulture);
            }
        }
        
        public static string CarModel {
            get {
                return ResourceManager.GetString("CarModel", resourceCulture);
            }
        }
        
        public static string CarType {
            get {
                return ResourceManager.GetString("CarType", resourceCulture);
            }
        }
        
        public static string GasRefill {
            get {
                return ResourceManager.GetString("GasRefill", resourceCulture);
            }
        }
        
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        public static string TrackLocation {
            get {
                return ResourceManager.GetString("TrackLocation", resourceCulture);
            }
        }
        
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string ErrorHeader {
            get {
                return ResourceManager.GetString("ErrorHeader", resourceCulture);
            }
        }
        
        public static string RequestId {
            get {
                return ResourceManager.GetString("RequestId", resourceCulture);
            }
        }
        
        public static string WebApplication {
            get {
                return ResourceManager.GetString("WebApplication", resourceCulture);
            }
        }
        
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        public static string UpdatedBy {
            get {
                return ResourceManager.GetString("UpdatedBy", resourceCulture);
            }
        }
        
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
    }
}
