image: tmaier/docker-compose:latest
build-job:
  only:
    - master
  stage: build
  script:
    - cd ./WebApplication
    - docker build . -t webapp
    - docker login -u kilpkonn -p "$CI_DOCKERHUB_TOKEN"
    - docker push "kilpkonn/icd0009-webapp"

