//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Base {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resource.Base.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ErrorMessage_MaxLength {
            get {
                return ResourceManager.GetString("ErrorMessage_MaxLength", resourceCulture);
            }
        }
        
        public static string ErrorMessage_MinLength {
            get {
                return ResourceManager.GetString("ErrorMessage_MinLength", resourceCulture);
            }
        }
        
        public static string ErrorMessage_Required {
            get {
                return ResourceManager.GetString("ErrorMessage_Required", resourceCulture);
            }
        }
        
        public static string ErrorMessage_StringLengthMax {
            get {
                return ResourceManager.GetString("ErrorMessage_StringLengthMax", resourceCulture);
            }
        }
        
        public static string ErrorMessage_StringLengthMinMax {
            get {
                return ResourceManager.GetString("ErrorMessage_StringLengthMinMax", resourceCulture);
            }
        }
        
        public static string ErrorMessage_Range {
            get {
                return ResourceManager.GetString("ErrorMessage_Range", resourceCulture);
            }
        }
        
        public static string ErrorMessage_ValueIsInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_ValueIsInvalid", resourceCulture);
            }
        }
        
        public static string ErrorMessage_AttemptedValueIsInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_AttemptedValueIsInvalid", resourceCulture);
            }
        }
        
        public static string ErrorMessage_MissingBindRequiredValue {
            get {
                return ResourceManager.GetString("ErrorMessage_MissingBindRequiredValue", resourceCulture);
            }
        }
        
        public static string ErrorMessage_MissingKeyOrValue {
            get {
                return ResourceManager.GetString("ErrorMessage_MissingKeyOrValue", resourceCulture);
            }
        }
        
        public static string ErrorMessage_MissingRequestBodyRequiredValue {
            get {
                return ResourceManager.GetString("ErrorMessage_MissingRequestBodyRequiredValue", resourceCulture);
            }
        }
        
        public static string ErrorMessage_NonPropertyAttemptedValueIsInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_NonPropertyAttemptedValueIsInvalid", resourceCulture);
            }
        }
        
        public static string ErrorMessage_NonPropertyUnknownValueIsInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_NonPropertyUnknownValueIsInvalid", resourceCulture);
            }
        }
        
        public static string ErrorMessage_NonPropertyValueMustBeANumber {
            get {
                return ResourceManager.GetString("ErrorMessage_NonPropertyValueMustBeANumber", resourceCulture);
            }
        }
        
        public static string ErrorMessage_UnknownValueIsInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_UnknownValueIsInvalid", resourceCulture);
            }
        }
        
        public static string ErrorMessage_ValueMustBeANumber {
            get {
                return ResourceManager.GetString("ErrorMessage_ValueMustBeANumber", resourceCulture);
            }
        }
        
        public static string ErrorMessage_ValueMustNotBeNull {
            get {
                return ResourceManager.GetString("ErrorMessage_ValueMustNotBeNull", resourceCulture);
            }
        }
        
        public static string ErrorMessage_NotValidPhone {
            get {
                return ResourceManager.GetString("ErrorMessage_NotValidPhone", resourceCulture);
            }
        }
        
        public static string ErrorMessage_Email {
            get {
                return ResourceManager.GetString("ErrorMessage_Email", resourceCulture);
            }
        }
        
        public static string ErrorMessage_DisplayNameLength {
            get {
                return ResourceManager.GetString("ErrorMessage_DisplayNameLength", resourceCulture);
            }
        }
        
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
    }
}
