//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Base.Base.Domain.Identity {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BaseUser {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseUser() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Resource.Base.Base.Domain.Identity.BaseUser", typeof(BaseUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        public static string NormalizedUserName {
            get {
                return ResourceManager.GetString("NormalizedUserName", resourceCulture);
            }
        }
        
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        public static string NormalizedEmail {
            get {
                return ResourceManager.GetString("NormalizedEmail", resourceCulture);
            }
        }
        
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        public static string PasswordHash {
            get {
                return ResourceManager.GetString("PasswordHash", resourceCulture);
            }
        }
        
        public static string SecurityStamp {
            get {
                return ResourceManager.GetString("SecurityStamp", resourceCulture);
            }
        }
        
        public static string ConcurrencyStamp {
            get {
                return ResourceManager.GetString("ConcurrencyStamp", resourceCulture);
            }
        }
        
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        public static string PhoneNumberConfirmed {
            get {
                return ResourceManager.GetString("PhoneNumberConfirmed", resourceCulture);
            }
        }
        
        public static string TwoFactorEnabled {
            get {
                return ResourceManager.GetString("TwoFactorEnabled", resourceCulture);
            }
        }
        
        public static string LockoutEnd {
            get {
                return ResourceManager.GetString("LockoutEnd", resourceCulture);
            }
        }
        
        public static string LockoutEnabled {
            get {
                return ResourceManager.GetString("LockoutEnabled", resourceCulture);
            }
        }
        
        public static string AccessFailedCount {
            get {
                return ResourceManager.GetString("AccessFailedCount", resourceCulture);
            }
        }
    }
}
